config/routes.rb
DemoApp::Application.routes.draw do
  root :to => "messages#index"

  resources :users, :except => [:destroy] do
    member do
      get :follower, :following
    end
  end

  resources :messages, :only => [:index, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :user_sessions, :only => [:new, :create, :destroy]

  match "login" => "user_sessions#new"
  match "logout" => "user_sessions#destroy"
  match "edit_profile" => "users#edit"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :user_id
  validates :user, :presence => true 
  validates :user_id, :presence => true 
  validates :content, :presence => true

  default_scope :order => "created_at DESC" 
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :following, :class_name => "User"
  attr_accessible :follower_id, :following_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages

  has_many :relationships, :foreign_key => :follower_id
  has_many :following_users, :through => :relationships, :source => :following

  has_many :reverse_relationships, :class_name => "Relationship", :foreign_key => :following_id
  has_many :follower_users, :through => :reverse_relationships, :source => :follower

  acts_as_authentic

  validates :name, :presence => true
  validates :email, :presence => true
  attr_accessible  :email, :name, :password, :password_confirmation

  def feed
    # get all post from following users included self post
        monitored_user_id = following_users.map(&:id) << self.id
        Message.where(:user_id => monitored_user_id)
  end

  def following?(user)
    relationships.exists?(:following_id => user)
  end

  def follow(user_id)
    relationships.create(:following_id => user_id)
  end

  def unfollow(user_id)
    relationships.find_by_following_id(user_id).destroy
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

  helper_method :current_user, :current_user_session

  def current_user_session
    return @current_user_session if @current_user_session
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if @current_user
    @current_user = current_user_session && current_user_session.record
  end

  def require_login
    unless current_user
      flash[:error] = "Please login first."
      redirect_to login_url
    end
  end

  def require_not_login
    if current_user
      flash[:error] = "You're already logged in."
      redirect_to request.env["HTTP_REFERER"] || root_url
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
  
  def index
    @message = Message.new
  end

  def create
    @message = current_user.messages.new(params[:message])

    if @message.save
      flash[:notice] = "Post successfully."
      redirect_to root_url
    else
      render :action => "index"
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to :back
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:relationship][:following_id])
    redirect_to user_url(params[:relationship][:following_id])
  end

  def destroy
    current_user.unfollow(params[:relationship][:following_id])
    redirect_to user_url(params[:relationship][:following_id])
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  before_filter :require_login, :only => [:destroy]
  before_filter :require_not_login, :only => [:new, :create]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Logged in successfully."
      redirect_to root_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logged out successfully."
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  before_filter :require_not_login, :only => [:new, :create]

  def index
    @users = User.all
  end

  # action show get id from post request then find user to show on views
  def show
    @user = User.find(params[:id])
    @relationship = Relationship.new

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = "Sign up successfully."
      redirect_to root_url
    else
      render :action => :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile was updated."
      redirect_to user_url(@user)
    else
      render :action => :edit
    end
  end

  def follower
     @user = User.find(params[:id])
     @followers = @user.follower_users
   end

   def following
     @user = User.find(params[:id])
     @followings = @user.following_users
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
﻿
<div id="header">
  <%= link_to "Message", root_url, :class => "site-name" %>
  <div id="navigation">
    <%= link_to "All users", users_url %>
    <% if current_user %>
        <%= link_to current_user.name, user_url(current_user) %>
        <%= link_to "Logout", logout_url %>
    <% else %>
        <%= link_to "Sign up", new_user_url %>
        <%= link_to "Login", login_url %>
    <% end %>
  </div>
</div>

<div id="content">
  ﻿
  <% if flash[:notice] %>
      <div class="notice-message">
        <%= flash[:notice] %>
      </div>
  <% end %>

  <% if flash[:error] %>
      <div class="error-message">
        <%= flash[:error] %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/messages/_post_body.html.erb
<div class="post-content"><%= post.content %></div>
<span class="post-time">posted <%= time_ago_in_words(post.created_at) %> ago.</span>
<% if post.user_id == current_user.id %>
    <%= link_to "delete", post,
                :method => :delete,
                :confirm => "Are you sure to delete this post?",
                :class => "delete-button" %>
<% end %>

app/views/messages/index.html.erb
<div class="user-information">
  <span class="user-name"><%= current_user.name %></span>
  <%= render :partial => "users/stats", :locals => {:user => current_user} %>

  <%= form_for @message do |f| %>
      <%= render :partial => "shared/form_error_messages", :locals => {:model_object => @message} %>
      <%= f.text_area :content, :placeholder => "What's on your mind?" %>
      <%= f.submit "Post" %>
  <% end %>
</div>

<div class="user-post">
  <h2>Feed</h2>

  <% if current_user.feed.empty? %>
      <p class="none">Not have any post yet.</p>
  <% else %>
      <% current_user.feed.each do |post| %>
          <div class="post">
            <p class="post-owner">
              <%= link_to post.user.name, user_url(post.user_id) %>
            </p>
            <%= render :partial => "post_body", :locals => {:post => post} %>
          </div>
      <% end %>
  <% end %>
</div>

app/views/shared/_form_error_messages.html.erb
<% if model_object.errors.any? %>
    <div class="error-message">
      <ul>
        <% model_object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/user_sessions/new.html.erb
<div id='login_form'>
  <h1>Login</h1>

  <%= form_for @user_session do |f| %>
      <%= render :partial => "shared/form_error_messages", :locals => { :model_object => @user_session} %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Login" %>
  <% end %>
</div>

app/views/users/_stats.html.erb
<div class="follower-followed">
  <span class="user-post-count first">
    <%= pluralize(user.messages.count, "post") %>
  </span>
  <span class="followed-user">
    <%= link_to "#{user.following_users.count} following", following_user_url(user.id) %>
  </span>
  <span class="follower-user">
     <%= link_to "#{user.follower_users.count} follower", follower_user_url(user.id) %>
  </span>
</div>

app/views/users/edit.html.erb
<div id="register_form">
  <h1>Edit Profile</h1>

  <%= form_for(@user) do |f| %>
      <%= render :partial => "shared/form_error_messages", :locals => {:model_object => @user} %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit %>
  <% end %>
</div>

app/views/users/follower.html.erb
<h1><%= @user.name %> Followers</h1>

<% if @followers.empty? %>
    <p class="none">You do not have any followers yet.</p>
<% else %>
    <% @followers.each do |user| %>
        <div class="user"><%= link_to user.name, user_url(user.id) %></div>
    <% end %>
<% end %>

app/views/users/following.html.erb
<h1><%= @user.name %> Followings</h1>

<% if @followings.empty? %>
    <p class="none">You are not following any user yet.</p>
<% else %>
    <% @followings.each do |user| %>
        <div class="user"><%= link_to user.name, user_url(user.id) %></div>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h1> All Users </h1>

<!-- Use each block to create link of user name-->
<% @users.each do |user| %>
    <div class="user"><%= link_to user.name, user_url(user.id) %></div>
<% end %>

app/views/users/new.html.erb
<div id="register_form">
  <h1>Sign up</h1>

  <%= form_for(@user) do |f| %>

      ﻿<%= render :partial => "shared/form_error_messages", :locals => { :model_object => @user} %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-information">
  <span class="user-name"><%= @user.name %></span>
  <% if @user == current_user %>
      <div class="edit-profile-button"><%= link_to "Edit profile", edit_profile_url %></div>
  <% else %>
      <% if current_user.following?(@user) %>
          <div class="unfollow-button">
            <%= form_for current_user.relationships.find_by_following_id(@user),
                         :html => {:method => :delete} do |f| %>
                <%= f.hidden_field :following_id %>
                <%= f.submit "Unfollow" %>
            <% end %>
          </div>
      <% else %>
          <div class="follow-button">
            <%= form_for @relationship do |f| %>
                <%= f.hidden_field :following_id, :value => @user.id %>
                <%= f.submit "Follow" %>
            <% end %>
          </div>
      <% end %>

  <% end %>
</div>

<div class="user-post">
  <h2>Feed</h2>

  <% if @user.messages.empty? %>
      <p class="none">Not have any post yet.</p>
  <% else %>
      <% @user.messages.each do |post| %>
          <div class="post">
            <%= render :partial => "messages/post_body", :locals => {:post => post} %>
          </div>
      <% end %>
  <% end %>

</div>